[project]
name = "toto_cli"
version = "1.0.0"
description = "SG Toto CLI"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
toto_cli = "toto_cli.cli:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"